pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "paraggautam1/devsecops-app:${BUILD_NUMBER}"
        SONARQUBE = "sonar-server"
    }

    stages {

        stage('SonarQube Scan') {
    steps {
        withSonarQubeEnv('sonar-server') {
            sh '''
            docker run --rm --network host \
              -v $(pwd):/usr/src \
              -e SONAR_HOST_URL=$SONAR_HOST_URL \
              sonarsource/sonar-scanner-cli \
              -Dsonar.projectKey=devsecops-app \
              -Dsonar.sources=app \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_AUTH_TOKEN \
              -Dsonar.scanner.metadataFilePath=/usr/src/report-task.txt
            '''
        }
    }
}

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE app/'
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh '''
echo $PASS | docker login -u $USER --password-stdin
docker push $DOCKER_IMAGE
'''
                }
            }
        }

        stage('Deploy to Kubernetes') {
    steps {
        sh '''
        kubectl set image deployment/devsecops-app app=$DOCKER_IMAGE
        kubectl set env deployment/devsecops-app VERSION=${BUILD_NUMBER}
        kubectl rollout status deployment/devsecops-app
        '''
    }
}
    }
}
